
set(FILES
    Include/metapulseWorld/metapulseWorldBus.h
    Include/metapulseWorld/metapulseWorldTypeIds.h
    Source/metapulseWorldSystemComponent.cpp
    Source/metapulseWorldSystemComponent.h
    Source/Components/User.h
    Source/Components/User.cpp
    Source/Components/UserCamera.h
    Source/Components/UserCamera.cpp
    Source/Components/Interfaces/UserBus.h
    Source/Components/Interfaces/UserBus.h
    Source/Components/StartMenuComponent.h
    Source/Components/StartMenuComponent.cpp
    Source/Components/Interfaces/StartMenuBus.h
    Source/Components/UserRegistry.h
    Source/Components/UserRegistry.cpp
    Source/Components/Interfaces/UserRegistryBus.h
    Source/Helpers/NetworkTypes.h
)
