set(FILES
	Source/Components/APIRequestsComponent.cpp
	Source/Components/APIRequestsComponent.h
	Source/Components/Interfaces/APIRequestsBus.h
	Source/Components/UIAdminComponent.h
	Source/Components/UIAdminComponent.cpp
	Source/Components/IngameMenuComponent.h
	Source/Components/IngameMenuComponent.cpp
	Source/Components/Interfaces/UIAdminBus.h
	Source/Components/InventoryMenuComponent.h
	Source/Components/InventoryMenuComponent.cpp
	Source/Components/HUDComponent.h
	Source/Components/HUDComponent.cpp
	Source/Components/Interfaces/HUDBus.h
	Source/Components/NotificationComponent.h
	Source/Components/NotificationComponent.cpp
	Source/Components/TradeMenuComponent.h
	Source/Components/TradeMenuComponent.cpp
	Source/Components/ChatBoxComponent.h
	Source/Components/ChatBoxComponent.cpp
)